require File.join(File.dirname(__FILE__), 'ruwrf', 'wrf_pre')
require File.join(File.dirname(__FILE__), 'ruwrf', 'wrf_real')
require File.join(File.dirname(__FILE__), 'ruwrf', 'wrf_run')
require File.join(File.dirname(__FILE__), 'ruwrf', 'run_wps')
require File.join(File.dirname(__FILE__), 'ruwrf', 'run_wrf')
